### ISSUE TITLE
Unit conversion from sm3 to bbl is inverted. 

### ISSUE THREAD

**Issue by mtcanam** [equinor/stea#46]
If I have an Eclipse vector in sm3, unit will equal SM3. If project units are Bbl, we get:
`unitfactor = self.units["Bbl"]["SM3"] = 1/6.2898`
Assuming the scale factor is 1 for simplicity. 
In the end, we multiply production by the unitconversion, which would end by dividing the metric production by 6.2898. This will give a far smaller result than intended. 2m3 would become 0.32 Bbl, which is incorrect.

All related to stea_request.py, line 75 onwards.

**Comment by berland** [comment]
Thanks for the bug report. Can you confirm that in your setting, the Eclipse simulation is in SM3 and your STEA project is set up with Bbl? (and not the other way around?)

**Comment by mtcanam** [comment]
Yes, I checked that out. I don't believe that's the issue unless there's something really funny going on in the background.

Michael
